/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FlappyUI from "./script/FlappyUI"
import FlappyControll from "./script/FlappyControll"
import BirdScript from "./script/BirdScript"
import PipeScript from "./script/PipeScript"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="flappy.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/FlappyUI.ts",FlappyUI);
        reg("script/FlappyControll.ts",FlappyControll);
        reg("script/BirdScript.ts",BirdScript);
        reg("script/PipeScript.ts",PipeScript);
    }
}
GameConfig.init();